// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCETLF_A0lvMwNtbxxBHkjHjhyXM17b0aQ',
    appId: '1:1034039902236:web:06c662da414ae0ab35dfd9',
    messagingSenderId: '1034039902236',
    projectId: 'store-app-d038a',
    authDomain: 'store-app-d038a.firebaseapp.com',
    databaseURL: 'https://store-app-d038a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-app-d038a.appspot.com',
    measurementId: 'G-NKWQC23R9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJZZYZucxPAsxykYdymwfrYtwilBKO-ck',
    appId: '1:1034039902236:android:ebe549a991801d0235dfd9',
    messagingSenderId: '1034039902236',
    projectId: 'store-app-d038a',
    databaseURL: 'https://store-app-d038a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-app-d038a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXpCW4avqy2I0KeX1oXCPC7f-NvHCt3o',
    appId: '1:1034039902236:ios:7d57918532b1361335dfd9',
    messagingSenderId: '1034039902236',
    projectId: 'store-app-d038a',
    databaseURL: 'https://store-app-d038a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-app-d038a.appspot.com',
    androidClientId: '1034039902236-21vk3ilcd70jmfqsm6qr79ine6t9d80l.apps.googleusercontent.com',
    iosClientId: '1034039902236-q9tj408mbhkr5gsvchten5l1e9iskk54.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopOwnerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRXpCW4avqy2I0KeX1oXCPC7f-NvHCt3o',
    appId: '1:1034039902236:ios:7d57918532b1361335dfd9',
    messagingSenderId: '1034039902236',
    projectId: 'store-app-d038a',
    databaseURL: 'https://store-app-d038a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-app-d038a.appspot.com',
    androidClientId: '1034039902236-21vk3ilcd70jmfqsm6qr79ine6t9d80l.apps.googleusercontent.com',
    iosClientId: '1034039902236-q9tj408mbhkr5gsvchten5l1e9iskk54.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopOwnerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCETLF_A0lvMwNtbxxBHkjHjhyXM17b0aQ',
    appId: '1:1034039902236:web:24d77db7cc41197035dfd9',
    messagingSenderId: '1034039902236',
    projectId: 'store-app-d038a',
    authDomain: 'store-app-d038a.firebaseapp.com',
    databaseURL: 'https://store-app-d038a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'store-app-d038a.appspot.com',
    measurementId: 'G-YZHXQPZ6DQ',
  );
}
